site_name: FBotics Documentation
theme: material
site_description: 'Documentation for FBotics, the Python Client for Facebook Send API'
docs_dir: sources
site_url: https://pasmod.github.io/fbotics/

markdown_extensions:
  - codehilite

dev_addr: '0.0.0.0:8000'

nav:
- Home: index.md
- Send API:
  - Client: send/client.md
  - Request: send/request.md
  - Recipient: send/recipient.md
  - Message: send/message.md
  - Attachment: send/attachment.md
- Quick Replies:
  - Quick Reply: quick_replies/quick_replies.md
  - Example: quick_replies/example.md
- Buttons: buttons/buttons.md
- Button Template:
  - Template Payload: _templates/button_template/button_template.md
  - Example: _templates/button_template/example.md
- Generic Template:
  - Template Payload: _templates/generic_template/generic_template.md
  - Example: _templates/generic_template/example.md
- Message: message.md
- Template Payloads: button_template.md
