site_name: FBotics Documentation
theme: material
site_description: 'Documentation for FBotics, the Python Client for Facebook Send API'
docs_dir: sources
site_url: https://pasmod.github.io/fbotics/

markdown_extensions:
  - codehilite

dev_addr: '0.0.0.0:8000'

nav:
- Home: index.md
- Client: client/client.md
- Quick Replies:
  - Quick Reply: quick_replies/quick_replies.md
  - Example: quick_replies/example.md
- Buttons: buttons/buttons.md
- Button Template: button_template/examples.md
- Generic Template:
  - Template Payload: generic_template/generic_template.md
  - Example: generic_template/example.md